# Generated by Django 5.1.7 on 2025-03-19 19:52

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimealert',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='downtimealert',
            name='app_downtim_sent_at_b3c707_idx',
        ),
        migrations.RemoveIndex(
            model_name='performancemetrics',
            name='app_perform_last_up_151f9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='uptimelog',
            name='app_uptimel_checked_4d7c76_idx',
        ),
        migrations.RemoveIndex(
            model_name='uptimelog',
            name='app_uptimel_status__48f612_idx',
        ),
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='downtimealert',
            name='alert_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='downtimealert',
            name='alert_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10),
        ),
        migrations.AlterField(
            model_name='downtimealert',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downtimealert',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='avg_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='downtime_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='total_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uptimelog',
            name='checked_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uptimelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uptimelog',
            name='response_time',
            field=models.FloatField(help_text='ms'),
        ),
        migrations.AlterField(
            model_name='uptimelog',
            name='status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('SLOW', 'Slow Response')], db_index=True, default='UP', max_length=10),
        ),
        migrations.AlterField(
            model_name='uptimelog',
            name='status_code',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='check_interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='expected_status_code',
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='owner_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(db_index=True, unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AddIndex(
            model_name='downtimealert',
            index=models.Index(fields=['website', 'alert_status'], name='app_downtim_website_4575f3_idx'),
        ),
        migrations.AddIndex(
            model_name='uptimelog',
            index=models.Index(fields=['website', 'checked_at'], name='app_uptimel_website_7515a5_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['owner', 'is_active'], name='app_website_owner_i_b48717_idx'),
        ),
    ]
